config/routes.rb
Rails.application.routes.draw do

  
  root to: "pages#home"
  get '/about',to: 'pages#about'
  get '/contact', to: 'pages#contact'

  resources :brands, only: [:show, :index]
  resources :products, only: :show
  resources :subscribers, only: [:new, :create]

  
  namespace :admin do  
    get "/" => "administrators#new_session"
    post "/" => "administrators#create_session"
    delete "/" => "administrators#destroy_session"

    resources :brands do
      resources :products, shallow: true
    end
    resources :subscribers, only: [:index, :destroy]

    get 'pages/search'
    post 'products/search'
  end

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
    has_secure_password validations: false
    validates :account, presence: true, uniqueness: true
    validates :password, presence: true, on: :create, length:{minimum: 3}
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :imageable, polymorphic: true, touch: true
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  include Sluggable

  has_many :products, dependent: :destroy
  has_one :seo_info, as: :seoable

  has_many :banners, as: :imageable, dependent: :destroy
  has_one :display_photo, as: :imageable, dependent: :destroy

  validates :title, presence: true
  
  accepts_nested_attributes_for :banners, :reject_if => :all_blank, allow_destroy: true
  accepts_nested_attributes_for :display_photo, :reject_if => :all_blank, allow_destroy: true
  
  sluggable_column :title


end

app/models/concerns/sluggable.rb
# sluggable_ryan gem
module Sluggable
  extend ActiveSupport::Concern

  included do
    before_save :generate_slug!
    class_attribute :slug_column 
  end

  def to_param
    self.slug
  end

  def generate_slug!
    the_slug = to_slug( self.send(self.class.slug_column.to_sym) )
    obj = self.class.find_by slug: the_slug
    count = 2
    while obj && obj != self
      the_slug = append_suffix(the_slug, count)
      obj = self.class.find_by slug: the_slug
      count += 1
    end
    self.slug = the_slug
  end

  def append_suffix(str, count)
    if str.split('-').last.to_i != 0
      return str.split('-').slice(0...-1).join('-') + '-' + count.to_s
    else
      return str + '-' + count.to_s
    end
  end

  def to_slug(title)
    str = title.strip
    # \p{Han} will matcch all chinese characters
    str.gsub! /\s*[^A-Za-z0-9\p{Han}]\s*/, '-'
    str.gsub! /-+/, "-"
    str.downcase
  end

  module ClassMethods
    def sluggable_column(col_name)
      self.slug_column = col_name
    end
  end

end

app/models/display_photo.rb
class DisplayPhoto < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :imageable, polymorphic: true, touch: true
end

app/models/photo.rb
#TODO: deprecated. This class should be delete
class Photo < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :imageable, polymorphic: true, touch: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  include Sluggable

  belongs_to :brand
  has_one :seo_info, as: :seoable

  has_many :banners, as: :imageable, dependent: :destroy
  has_one :display_photo, as: :imageable, dependent: :destroy

  validates :title, presence: true

  accepts_nested_attributes_for :banners, :reject_if => :all_blank, allow_destroy: true
  accepts_nested_attributes_for :display_photo, :reject_if => :all_blank, allow_destroy: true

  sluggable_column :title



  # before_save :convert_youtube_url

  # def convert_youtube_url 
  #   if self.video_url?
  #     self.video_url = VideoInfo.new(self.video_url).embed_url
  #   end
  # end

  def youtube_embed_url
    VideoInfo.new(self.video_url).embed_url if self.video_url?
  end

end

app/models/seo_info.rb
class SeoInfo < ActiveRecord::Base

  belongs_to :seoable, polymorphic: true
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base

  after_save :subscribe

  validates :email, presence: true


  def subscribe
    @list_id = ENV['MAILCHIMP_LIST_ID']
    gb = Gibbon::API.new
    
    gb.lists.subscribe({
      :id => @list_id,
      :email => {:email => self.email}
    })
  end

  def created_today?
    self.created_at.to_date == Date.today
  end

end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < AdminController
  def search
    @q = Product.ransack(params[:q]) 
    @products = Product.none
  end
end

app/controllers/admin/subscribers_controller.rb
class Admin::SubscribersController < AdminController
  before_action :find_subscriber, only: :destroy

  def index
    @subscribers = Subscriber.order(id: :desc).paginate(:page => params[:page], :per_page=>50)
  end


  def destroy
    if @subscriber.destroy
      flash[:notice] = "成功刪除訂閱者"
      redirect_to admin_subscribers_path
    else 
      flash[:error] = "刪除訂閱者失敗"
      redirect_to :back
    end
  end



  private

  def find_subscriber
    @subscriber = Subscriber.find(params[:id])
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  layout "admin"

  #before_action :authenticate_administrator!
  #before_action :admin_required, :except => [:new_session, :create_session]
  before_action :require_administrator, except: [:new_session, :create_session]

  

  helper_method :current_administrator, :logged_in?

  def require_administrator
    access_denied unless logged_in?
  end

  def access_denied
    flash[:error] = "Must be login to do that"
    redirect_to admin_path
  end

  def logged_in?
    !!current_administrator
  end

  def current_administrator
    @current_administrator ||= find_administrator
  end

  def find_administrator
    administrator = Administrator.find_by(id: session[:administrator_id])
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :find_brand, only: :show

  def index
    @brands = Brand.order(id: :asc)
  end

  def show
    @products = @brand.products.order(id: :desc).paginate(:page => params[:page], :per_page => 15)
  end


  private

  def find_brand
    @brand = Brand.includes(:products, :banners, :display_photo).find_by(slug: params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @products = Product.order(id: :desc).paginate(:page => params[:page], :per_page => 15) #.limit(6)
  end


  def about
  end

  def contact
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: :show

  def show
  end



  private

  def find_product
    @product = Product.includes(:brand, :banners, :display_photo).find_by(slug: params[:id])
  end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  
  def new
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      flash[:notice] = "您已成功註冊會員，請前往 Email 確認訂閱電子報，謝謝：）"
      redirect_to new_subscriber_path
    else
      flash.now[:error] = "註冊失敗，請確認欄位沒有空白"
      render :new
    end

  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:name, :line, :email, :phone_number)
  end


end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/subscribers_helper.rb
module Admin::SubscribersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/subscribers/index.html.erb
<span style="font-size: 32px;">管理訂閱者</span> <span>(依照註冊)</span> <span>(藍色表示今天註冊的使用者)</span>


<div class="divider"></div>

<div class="row">
  <div class="col-md-12 well">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Email</th>
          <th>姓名</th>
          <th>手機</th>
          <th>line</th>
          <th>刪除</th>

        </tr>
      </thead>
  
      <tbody>

          <%@subscribers.each do |subscriber|%>
            <%if subscriber.created_today?%>
              <tr class="info">
            <% else %>
              <tr>
            <% end %>
  
              <td><%= subscriber.id %></td>
              <td><%= subscriber.email %> </td>
              <td><%= subscriber.name %></td>
              <td><%= subscriber.phone_number %></td>
              <td><%= subscriber.line %></td>
     
              <td><%= link_to('刪除', admin_subscriber_path(subscriber), :method => :delete, :class=>'btn btn-danger btn-sm', data: { confirm: "確定要刪除該名訂閱者？" }) %></td>
            </tr>
          
          <%end%> 

      </tbody>


    </table>
  </div>
</div>

<div style="text-align: center;">
<%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>

app/views/subscribers/new.html.erb
<!-- 內容-->
<div class="container down-lg ">
    <div class="col-md-4 col-xs-12">

        <%= render partial: 'shared/errors', locals: {obj: @subscriber} %>
        <!-- 表單 -->
        <div class="col-md-10 ">
            <h2></h2>
            <h2>加入會員 <small class="subtitle">  Join Member</small></h2>
        </div>

        <%= form_for(@subscriber, html: { class: "form-inline"} ) do |f| %>
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-addon">姓名</div>
              <%= f.text_field(:name, class: "form-control", placeholder: "") %>
            </div>

            <div class="input-group">
              <div class="input-group-addon">LINE帳號</div>
              <%= f.text_field(:line, class: "form-control", placeholder: "") %>
            </div>

            <div class="input-group">
              <div class="input-group-addon">手機</div>
              <%= f.text_field(:phone_number, class: "form-control", placeholder: "") %>
            </div>

            <div class="input-group">
              <div class="input-group-addon">信箱(必填)</div>
              <%= f.text_field(:email, class: "form-control" , placeholder: "") %>
            </div>

            <div class="col-md-10 col-md-offset-1">
              <%= f.submit("加入會員", class: "btn btn-primary", style: "font-size:30px; color:white;") %>
              <!-- <button type="submit" class="btn btn-primary">
              <h2 style="color:white;">加入會員</h2></button> -->
            </div>
          </div>
        <% end %>
         <!-- <form class="form-inline">
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">姓名</div>
                    <input type="text" class="form-control" id="" placeholder="">
                </div>
                <div class="input-group">
                    <div class="input-group-addon">LINE帳號</div>
                    <input type="text" class="form-control" id="" placeholder="">
                </div>
                <div class="input-group">
                    <div class="input-group-addon">手機</div>
                    <input type="text" class="form-control" id="" placeholder="">
                </div>
                <div class="input-group">
                    <div class="input-group-addon">信箱</div>
                    <input type="text" class="form-control" id="" placeholder="">
                </div>
                <div class="col-md-10 col-md-offset-1">
                    <button type="submit" class="btn btn-primary">
                        <h2 style="color:white;">加入會員</h2></button>
                </div>
        </form> --> 
    </div>

    <div class="col-md-8 col-xs-12">
        <div class="col-md-6 text-center down-md">
          <%= image_tag('home06.png', class: "img-responsive col-md-12") %>
            <!-- <img src="img/home06.png" class="img-responsive col-md-12 "> -->
          </br>
          <%= image_tag('contact02s.png', class: "img-responsive col-md-12") %>
            <!-- <img src="img/contact02s.png" class="img-responsive col-md-12 "> -->
        </div>
        <div class="col-md-6 text-left">
          <%= image_tag('contact01.png', class: "img-responsive col-md-12") %>
            <!-- <img src="img/contact01.png" class="img-responsive "> -->
        </div>
        <div class="row text-left down-xs">
          <%= image_tag('contact03.png', class: "img-responsive col-md-12") %>
            <!-- <img src="img/contact03.png" class="img-responsive"> -->
        </div>
    </div>
    <div class="col-md-12 col-xs-12 " style="height:70px;">
    </div>
</div>