config/routes.rb
Rails.application.routes.draw do

  
  root to: "pages#home"
  get '/about',to: 'pages#about'
  get '/contact', to: 'pages#contact'

  resources :brands, only: [:show, :index]
  resources :products, only: :show
  resources :subscribers, only: [:new, :create]

  
  namespace :admin do  
    get "/" => "administrators#new_session"
    post "/" => "administrators#create_session"
    delete "/" => "administrators#destroy_session"

    resources :brands do
      resources :products, shallow: true
    end
    resources :subscribers, only: [:index, :destroy]

    get 'pages/search'
    post 'products/search'
  end

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
    has_secure_password validations: false
    validates :account, presence: true, uniqueness: true
    validates :password, presence: true, on: :create, length:{minimum: 3}
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :imageable, polymorphic: true, touch: true
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  include Sluggable

  has_many :products, dependent: :destroy
  has_one :seo_info, as: :seoable

  has_many :banners, as: :imageable, dependent: :destroy
  has_one :display_photo, as: :imageable, dependent: :destroy

  validates :title, presence: true
  
  accepts_nested_attributes_for :banners, :reject_if => :all_blank, allow_destroy: true
  accepts_nested_attributes_for :display_photo, :reject_if => :all_blank, allow_destroy: true
  
  sluggable_column :title


end

app/models/concerns/sluggable.rb
# sluggable_ryan gem
module Sluggable
  extend ActiveSupport::Concern

  included do
    before_save :generate_slug!
    class_attribute :slug_column 
  end

  def to_param
    self.slug
  end

  def generate_slug!
    the_slug = to_slug( self.send(self.class.slug_column.to_sym) )
    obj = self.class.find_by slug: the_slug
    count = 2
    while obj && obj != self
      the_slug = append_suffix(the_slug, count)
      obj = self.class.find_by slug: the_slug
      count += 1
    end
    self.slug = the_slug
  end

  def append_suffix(str, count)
    if str.split('-').last.to_i != 0
      return str.split('-').slice(0...-1).join('-') + '-' + count.to_s
    else
      return str + '-' + count.to_s
    end
  end

  def to_slug(title)
    str = title.strip
    # \p{Han} will matcch all chinese characters
    str.gsub! /\s*[^A-Za-z0-9\p{Han}]\s*/, '-'
    str.gsub! /-+/, "-"
    str.downcase
  end

  module ClassMethods
    def sluggable_column(col_name)
      self.slug_column = col_name
    end
  end

end

app/models/display_photo.rb
class DisplayPhoto < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :imageable, polymorphic: true, touch: true
end

app/models/photo.rb
#TODO: deprecated. This class should be delete
class Photo < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :imageable, polymorphic: true, touch: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  include Sluggable

  belongs_to :brand
  has_one :seo_info, as: :seoable

  has_many :banners, as: :imageable, dependent: :destroy
  has_one :display_photo, as: :imageable, dependent: :destroy

  validates :title, presence: true

  accepts_nested_attributes_for :banners, :reject_if => :all_blank, allow_destroy: true
  accepts_nested_attributes_for :display_photo, :reject_if => :all_blank, allow_destroy: true

  sluggable_column :title



  # before_save :convert_youtube_url

  # def convert_youtube_url 
  #   if self.video_url?
  #     self.video_url = VideoInfo.new(self.video_url).embed_url
  #   end
  # end

  def youtube_embed_url
    VideoInfo.new(self.video_url).embed_url if self.video_url?
  end

end

app/models/seo_info.rb
class SeoInfo < ActiveRecord::Base

  belongs_to :seoable, polymorphic: true
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base

  after_save :subscribe

  validates :email, presence: true


  def subscribe
    @list_id = ENV['MAILCHIMP_LIST_ID']
    gb = Gibbon::API.new
    
    gb.lists.subscribe({
      :id => @list_id,
      :email => {:email => self.email}
    })
  end

  def created_today?
    self.created_at.to_date == Date.today
  end

end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < AdminController

  before_action :find_brand, only: [:show, :edit, :update, :destroy]


  def index
    @brands = Brand.order(id: :asc) #.paginate(page: params[:page], per_page: 20)
  end

  def show
    @products = @brand.products.order(id: :asc)
  end

  def new
    @brand = Brand.new
    @display_photo = @brand.build_display_photo
    #@brand.addTwoPhotos
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      flash[:notice] = "成功新增一項品牌"
      redirect_to admin_path
    else
      flash[:error] = "抱歉，沒有新增成功，請再試一次"
      render :new
    end

  end

  def edit
    @display_photo =  @brand.display_photo || @brand.build_display_photo
  end

  def update
    if @brand.update(brand_params)
      flash[:notice] = "修改成功"
      redirect_to admin_path
    else
      flash[:notice] = "修改失敗"
      render :edit
    end
  end

  def destroy
    if @brand.destroy
      flash[:notice] = "成功刪除品牌"
      redirect_to admin_path
    else
      flash[:error] = "沒有刪除品牌"
      redirect_to :back
    end

  end


  private
  def find_brand
    @brand = Brand.includes(:banners, :display_photo).find_by(slug: params[:id])
  end

  def brand_params
    params.require(:brand).permit(:chinese_title, :title, :description, :banners_attributes => [:id, :image, :_destroy], :display_photo_attributes => [:id, :image, :_destroy])
  end


end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < AdminController
  def search
    @q = Product.ransack(params[:q]) 
    @products = Product.none
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  layout "admin"

  #before_action :authenticate_administrator!
  #before_action :admin_required, :except => [:new_session, :create_session]
  before_action :require_administrator, except: [:new_session, :create_session]

  

  helper_method :current_administrator, :logged_in?

  def require_administrator
    access_denied unless logged_in?
  end

  def access_denied
    flash[:error] = "Must be login to do that"
    redirect_to admin_path
  end

  def logged_in?
    !!current_administrator
  end

  def current_administrator
    @current_administrator ||= find_administrator
  end

  def find_administrator
    administrator = Administrator.find_by(id: session[:administrator_id])
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :find_brand, only: :show

  def index
    @brands = Brand.order(id: :asc)
  end

  def show
    @products = @brand.products.order(id: :desc).paginate(:page => params[:page], :per_page => 15)
  end


  private

  def find_brand
    @brand = Brand.includes(:products, :banners, :display_photo).find_by(slug: params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @products = Product.order(id: :desc).paginate(:page => params[:page], :per_page => 15) #.limit(6)
  end


  def about
  end

  def contact
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: :show

  def show
  end



  private

  def find_product
    @product = Product.includes(:brand, :banners, :display_photo).find_by(slug: params[:id])
  end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  
  def new
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      flash[:notice] = "您已成功註冊會員，請前往 Email 確認訂閱電子報，謝謝：）"
      redirect_to new_subscriber_path
    else
      flash.now[:error] = "註冊失敗，請確認欄位沒有空白"
      render :new
    end

  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:name, :line, :email, :phone_number)
  end


end

app/helpers/admin/administrators_helper.rb
module Admin::AdministratorsHelper
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/subscribers_helper.rb
module Admin::SubscribersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/brands/_form.html.erb
  <%= f.input :title, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "英文名稱(必填)" , :type=>"text"%>

  <%= f.input :chinese_title, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "中文名稱" , :type=>"text"%>


  <%= f.input :description, :input_html=>{:class =>"form-control", :rows=>"8"}, :wrapper_html=>{:class=>"form-group"}, :label=>"品牌描述"%>


  <hr>

  <h2>上傳品牌展示圖片</h2>


    <%= f.fields_for :display_photo, @display_photo  do |photo_form|%>

        <div class="nested-fields form-inline form-img-box">
      </br>
        <%= photo_form.input :image, :input_html=>{:class=>"form-control"}, :wrapper_html=>{:class=>"form-group"}, :label=>"上傳圖片"%>


        <%if !photo_form.object.image.nil?%>
             <%= image_tag(photo_form.object.image, :class=>"img-rounded")%>
        <%end%>


        <%#= photo_form.link_to_remove("Remove this photo", :class=>'btn btn-lg btn-danger') %>
      </div>
    <%end%>
    <%#= f.link_to_add "增加圖片", :display_photo, :class=>'btn btn-lg btn-info' %>

  
  <hr>

  <h2>上傳品牌內頁大圖</h2>


    <%= f.fields_for :banners, @brand.banners do |photo_form|%>
<!-- .order(id: :asc) -->
      <div class="nested-fields form-inline form-img-box">
        </br>
        <%=photo_form.input :image, :input_html=>{:class=>"form-control"}, :wrapper_html=>{:class=>"form-group"}, :label=>"上傳圖片"%>

        <%if !photo_form.object.image.nil?%>
             <%= image_tag(photo_form.object.image, :class=>"img-rounded")%>
        <%end%>


        <%= photo_form.link_to_remove("Remove this photo", :class=>'btn btn-lg btn-danger') %>
      </div>
    <%end%>
        <%= f.link_to_add "增加圖片", :banners, :class=>'btn btn-lg btn-info'  %>



 
  <hr>

app/views/admin/brands/edit.html.erb
<div class="">
  <h1>Edit Brand</h1>

  <%= render partial: 'shared/errors', locals: {obj: @brand} %>

  <%= simple_nested_form_for @brand, html: { multipart: true }, :url => admin_brand_path(@brand) do |f| %>

  <%= render(:partial=>'form', :locals=>{:f=>f})%>
 
  
  <div class="form-group">
    <%= f.submit '修改', class: "btn btn-primary btn-lg" %>

    <%= link_to('刪除', admin_brand_path(@brand), class: "btn btn-danger", method: :delete, 'data-confirm': "確定要刪除品牌嗎?") %>
  </div>

  <% end %>
</div>

app/views/admin/brands/index.html.erb
<h1>Admin panel</h1>
<hr>

<%= link_to("新增品牌", new_admin_brand_path, class: "btn btn-lg btn-info") %>


<%= link_to("登出", admin_path, class: "btn btn-lg btn-warning") %>

app/views/admin/brands/new.html.erb
<div class="">
  <h1>New Brand</h1>

  <%= render(partial: 'shared/errors', locals: {obj: @brand}) %>
  
  <%= simple_nested_form_for @brand, html: { multipart: true},:url => admin_brands_path do |f| %>


  <%= render(:partial=>'form', :locals=>{:f=>f})%>
 
  
  <div class="form-group">
    <%= f.submit '新增', class: "btn btn-primary btn-lg" %>
  </div>

  <% end %>
</div>

app/views/admin/brands/show.html.erb
<h2> 品牌: <%= @brand.title %> </h2>

<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增商品", new_admin_brand_product_path(@brand), :class => "btn btn-info btn-lg") %>
  <%= link_to("修改品牌", edit_admin_brand_path, :class => "btn btn-primary btn-lg") %>
  <%= link_to('刪除品牌', admin_brand_path(@brand), class: "btn btn-danger btn-lg", method: :delete, 'data-confirm': "確定要刪除品牌嗎?") %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>商品編號</th>
      <th>Product title</th>
      <th>Product Photo</th>
      <th>修改</th>
      <th>刪除</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'admin/products/product', collection: @products, as: :product %>
  </tbody>
</table>

app/views/brands/index.html.erb
<!-- ------------------- -->
    <!--品牌大圖 -->
    <div class="bg-brand hidden-xs">
        <div class="container" style="height:800px;">
            <div class="col-md-2 col-md-offset-5 col-xs-4 col-xs-offset-4 text-center">
            </div>
        </div>
    </div>
    <div class="bg-brand-m visible-xs">
        <div class="container" style="height:500px;">
            <div class="col-md-2 col-md-offset-5 col-xs-4 col-xs-offset-4 text-center">
            </div>
        </div>
    </div>
    <!-- 品牌精選 -->
    <div class="container" id="brand">
        <div class="col-md-4 col-md-offset-4 text-center">
          <%= image_tag("home01.png", class: "home01") %>
            <!-- <img src="img/home01.png" class="home01"> -->
        </div>
        <div class="col-md-11 col-md-offset-1 brand-list">

            <% @brands.each_with_index do |brand| %>
              <%= link_to(brand_path(brand)) do %>
                <div class="col-md-4   col-xs-12 ">
                  <ul class="list-inline brand_list">
                    <li></li>
                    <li class=" underline "> <%= brand.title %> </li>
                    <li><%= brand.chinese_title %></li>
                  </ul>
                </div>
              <% end %>
            <% end %>


            <!-- <div class="col-md-4 text-center  col-xs-6 ">
                <a href="item-list.html">
                    <ul class="list-inline">
                        <li></li>
                        <li class="underline">ROLEX</li>
                        <li>勞力士</li>
                    </ul>
                </a>
                <a href="item-list.html">
                    <ul class="list-inline">
                        <li></li>
                        <li class="underline">ROLEX</li>
                        <li>勞力士</li>
                    </ul>
                </a>
                <a href="item-list.html">
                    <ul class="list-inline">
                        <li></li>
                        <li class="underline">ROLEX</li>
                        <li>勞力士</li>
                    </ul>
                </a>
            </div>

            <div class="col-md-4 text-center col-xs-6 ">
                <a href="item-list.html">
                    <ul class="list-inline">
                        <li></li>
                        <li class="underline">ROLEX</li>
                        <li>勞力士</li>
                    </ul>
                </a>
                <a href="item-list.html">
                    <ul class="list-inline">
                        <li></li>
                        <li class="underline">ROLEX</li>
                        <li>勞力士</li>
                    </ul>
                </a>
                <a href="item-list.html">
                    <ul class="list-inline">
                        <li></li>
                        <li class="underline">ROLEX</li>
                        <li>勞力士</li>
                    </ul>
                </a>
            </div>
            <div class="col-md-4 text-center col-xs-6 ">
                <a href="item-list.html">
                    <ul class="list-inline">
                        <li></li>
                        <li class="underline">ROLEX</li>
                        <li>勞力士</li>
                    </ul>
                </a>
                <a href="item-list.html">
                    <ul class="list-inline">
                        <li></li>
                        <li class="underline">ROLEX</li>
                        <li>勞力士</li>
                    </ul>
                </a>
                <a href="item-list.html">
                    <ul class="list-inline">
                        <li></li>
                        <li class="underline">ROLEX</li>
                        <li>勞力士</li>
                    </ul>
                </a>
            </div> -->
            <div style="height:500px;"></div>
        </div>
    </div>

app/views/brands/show.html.erb
 <!-- 精選品牌列表  -->
<div class="container brand-contain " id="brand">
    <div class="col-md-12 inline brain-title">
        <div class="col-md-1 col-xs-2">
          <%= image_tag('brand01.png') %>
            <!-- <img src="img/brand01.png"> -->
        </div>
        <div class="col-md-8 title col-xs-12 hidden-xs  ">
            <h3><strong>BRAND 精選品牌</strong></h3>
            <p>||</p>
            <h4 class="fuck-font" style="color:#B79A77"> <%= @brand.title %> <%= @brand.chinese_title %> </h4>
        </div>
        <div class="col-md-8 title col-xs-10 visible-xs down-xs  text-left">
            <h4><strong class="fuck-fuck-font">BRAND 精選品牌</strong></h4>
        </div>
        <div class="col-xs-8   down-xs  visible-xs text-left">
            <h5 style="color:#B79A77"> <%= @brand.title %> <%= @brand.chinese_title %></h5>
        </div>
    </div>

    <% @products.each_with_index do |product, index| %>
      <% if(index%3 == 0)%>
          <div class="row">
      <% end %>
        <div class="col-md-4 down-sm hidden-xs">
          <%= link_to(product_path(product)) do %>
            <div class="pic"> 
              <%= image_tag(product.display_photo.try(:image_url), class: "watch_l_img") %>
            </div> 

            <h5 class="right-xs">#<%= product.number %></h5>

            <h4 class="right-xs"> <%= product.title %> </h4>

            <h4 class="right-xs">售價：<span class="fuck-color"> <%= product.price %></span> </h4>
          <% end %>
          <!-- <a href="detail.html"><h4 class="down-sm right-sm ">CHANEL陶瓷女用腕錶</h4></a> -->
          
          
        </div>

         <div class="col-xs-12 down-xs visible-xs">
          <%= link_to(product_path(product)) do %>
            <div class="phone_pic row"> 
              <%= image_tag(product.display_photo.try(:image_url), class: "watch_l_img") %>
              <%# image_tag('home03.png', class: "watch_l_img") %>
            </div> 
            <h5 class="right-xs">#<%= product.number %></h5>

            <h4 class="right-xs"> <%= product.title %> </h4>

            <h4 class="right-xs">售價：<span class="fuck-color"> <%= product.price %></span> </h4>

            
          <% end %>
          <!-- <a href="detail.html"><h4 class="down-sm right-sm ">CHANEL陶瓷女用腕錶</h4></a> -->
        
        </div>
      
      <% if(index%3 == 2 || index == @products.size - 1)%>
        </div>
      <% end %>

    <% end %>




    <div style = "text-align:center;">
      <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
    </div>

    <!-- <div class="col-md-3 col-md-offset-1  down-xl">
        <img src="img/home03.png">
        <a href="detail.html"><h4 class="down-sm right-sm ">CHANEL陶瓷女用腕錶</h4></a>
        <h5 class="right-sm">#9262</h5>
    </div>
    <div class="col-md-3 col-md-offset-1   down-xl">
        <img src="img/home03.png">
        <a href="detail.html"><h4 class="down-sm right-sm ">CHANEL陶瓷女用腕錶</h4></a>
        <h5 class="right-sm">#9262</h5>
    </div>
    <div class="col-md-3 col-md-offset-1  down-xl">
        <img src="img/home03.png">
        <a href="detail.html"><h4 class="down-sm right-sm ">CHANEL陶瓷女用腕錶</h4></a>
        <h5 class="right-sm">#9262</h5>
    </div>
    <div class="col-md-3 col-md-offset-1  down-xl">
        <img src="img/home03.png">
        <a href="detail.html"><h4 class="down-sm right-sm ">CHANEL陶瓷女用腕錶</h4></a>
        <h5 class="right-sm">#9262</h5>
    </div>
    <div class="col-md-3 col-md-offset-1   down-xl">
        <img src="img/home03.png">
        <a href="detail.html"><h4 class="down-sm right-sm ">CHANEL陶瓷女用腕錶</h4></a>
        <h5 class="right-sm">#9262</h5>
    </div>
    <div class="col-md-3 col-md-offset-1  down-xl">
        <img src="img/home03.png">
        <a href="detail.html"><h4 class="down-sm right-sm ">CHANEL陶瓷女用腕錶</h4></a>
        <h5 class=" right-sm">#9262</h5>
    </div> -->
</div>