config/routes.rb
Rails.application.routes.draw do

  
  root to: "pages#home"
  get '/about',to: 'pages#about'
  get '/contact', to: 'pages#contact'

  resources :brands, only: [:show, :index]
  resources :products, only: :show
  resources :subscribers, only: [:new, :create]

  
  namespace :admin do  
    get "/" => "administrators#new_session"
    post "/" => "administrators#create_session"
    delete "/" => "administrators#destroy_session"

    resources :brands do
      resources :products, shallow: true
    end
    resources :subscribers, only: [:index, :destroy]

    get 'pages/search'
    post 'products/search'
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  include Sluggable

  belongs_to :brand
  has_one :seo_info, as: :seoable

  has_many :banners, as: :imageable, dependent: :destroy
  has_one :display_photo, as: :imageable, dependent: :destroy

  validates :title, presence: true

  accepts_nested_attributes_for :banners, :reject_if => :all_blank, allow_destroy: true
  accepts_nested_attributes_for :display_photo, :reject_if => :all_blank, allow_destroy: true

  sluggable_column :title



  # before_save :convert_youtube_url

  # def convert_youtube_url 
  #   if self.video_url?
  #     self.video_url = VideoInfo.new(self.video_url).embed_url
  #   end
  # end

  def youtube_embed_url
    VideoInfo.new(self.video_url).embed_url if self.video_url?
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController

  before_action :find_brand, only: [:index, :new, :create]
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @product = @brand.products.build       
    @display_photo = @product.build_display_photo
  end

  def create
    @product = @brand.products.build(product_params)

    if @product.save
      flash[:notice] = "成功新增一項商品"
      redirect_to admin_brand_path(@product.brand)  # brand show
    else
      flash[:error] = "抱歉，沒有新增成功，請再試一次"
      render :new
    end

  end

  def edit
    @display_photo =  @product.display_photo || @product.build_display_photo
  end


  def update
    if @product.update(product_params)
      flash[:notice] = "修改成功"
      redirect_to admin_brand_path(@product.brand)  # brand show
    else
      flash[:notice] = "修改失敗"
      render :edit
    end
  end

  def destroy

    if @product.destroy
      flash[:notice] = "成功刪除商品"
      redirect_to admin_brand_path(@product.brand) # brand show
    else 
      flash[:error] = "沒有刪除商品"
      redirect_to :back
    end

  end



  def search
    @q = Product.ransack(params[:q]) 
    @products = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 30 )
    render 'admin/pages/search'
  end

  private

  def find_brand
    @brand = Brand.find_by( slug: params[:brand_id])
  end

  def find_product
    @product = Product.includes(:banners, :display_photo).find_by(slug: params[:id])
  end

  def product_params
    params.require(:product).permit(:number, :title, :description, :status, :mechanism, :case, :face, :function, :strap, :price, :video_url, :other, :banners_attributes => [:id, :image, :_destroy], :display_photo_attributes => [:id, :image, :_destroy])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: :show

  def show
  end



  private

  def find_product
    @product = Product.includes(:brand, :banners, :display_photo).find_by(slug: params[:id])
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
  <%= f.input :number, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "商品編號" , :type=>"text"%>
  
  <%= f.input :title, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "名稱" , :type=>"text"%>

  <%= f.input :status, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "狀況" , :type=>"text"%>

  <%= f.input :mechanism, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "機芯" , :type=>"text"%>

  <%= f.input :case, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "錶殼" , :type=>"text"%>

  <%= f.input :face, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "面盤" , :type=>"text"%>

  <%= f.input :function, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "功能" , :type=>"text"%>

  <%= f.input :strap, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "錶帶" , :type=>"text"%>

  <%= f.input :price, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "售價" , :type=>"text"%>

  <%= f.input :video_url, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "youtube 影片連結" , :type=>"text"%>

  <%= f.input :other, :input_html=>{:class => "form-control"}, :wrapper_html=>{ :class => "form-group"} ,:label => "其他" , :type=>"text"%>

  <%#= f.input :description, :input_html=>{:class =>"form-control", :rows=>"8"}, :wrapper_html=>{:class=>"form-group"}, :label=>"商品描述"%>




  <hr>

  <h2>上傳產品展示圖片</h2>


    <%= f.fields_for :display_photo, @product.display_photo  do |photo_form|%>

        <div class="nested-fields form-inline form-img-box">
      </br>
        <%= photo_form.input :image, :input_html=>{:class=>"form-control"}, :wrapper_html=>{:class=>"form-group"}, :label=>"上傳圖片"%>


        <%if !photo_form.object.image.nil?%>
             <%= image_tag(photo_form.object.image, :class=>"img-rounded")%>
        <%end%>


        <%#= photo_form.link_to_remove("Remove this photo", :class=>'btn btn-lg btn-danger') %>
      </div>
    <%end%>
    <%#= f.link_to_add "增加圖片", :display_photo, :class=>'btn btn-lg btn-info' %>

  
  <hr>

  <h2>上傳產品內頁大圖</h2>


    <%= f.fields_for :banners, @product.banners do |photo_form|%>
<!-- .order(id: :asc) -->
      <div class="nested-fields form-inline form-img-box">
        </br>
        <%=photo_form.input :image, :input_html=>{:class=>"form-control"}, :wrapper_html=>{:class=>"form-group"}, :label=>"上傳圖片"%>

        <%if !photo_form.object.image.nil?%>
             <%= image_tag(photo_form.object.image, :class=>"img-rounded")%>
        <%end%>


        <%= photo_form.link_to_remove("Remove this photo", :class=>'btn btn-lg btn-danger') %>
      </div>
    <%end%>
        <%= f.link_to_add "增加圖片", :banners, :class=>'btn btn-lg btn-info'  %>



 
  <hr>

app/views/admin/products/_product.html.erb
<tr>
  <td> 
    <%= product.id %>
  </td>

  <td> 
    <%= product.number %>
  </td>

  <td>
    <h3><%= link_to( product.title , product_path(product) )%></h3>   
  </td>
  <td>   
  <%=link_to admin_product_path(product) do%>     
    <%= image_tag(product.display_photo.try(:image_url), size: "200") %>
  <%end%>    
  </td>
  
  <td> <%= link_to("修改", edit_admin_product_path(product), class: "btn btn-warning btn-lg") %> </td>
  <td> <%= link_to("刪除", admin_product_path(product), class: "btn btn-danger btn-lg", method: :delete, 'data-confirm': "確定要刪除商品嗎?" ) %> </td>
</tr>

app/views/admin/products/edit.html.erb
<div class="">
  <h1>修改產品</h1>

  <%= render partial: 'shared/errors', locals: {obj: @product} %>

  <%= simple_nested_form_for @product, html: { multipart: true }, :url => admin_product_path(@product) do |f| %>

  <%= render(:partial=>'form', :locals=>{:f=>f})%>
 
  
  <div class="form-group">
    <%= f.submit '修改', class: "btn btn-primary btn-lg" %>

  </div>

  <% end %>
</div>

app/views/admin/products/new.html.erb
<div class="">
  <h1>新增產品</h1>

  <%= render partial: 'shared/errors', locals: {obj: @product} %>

  <%= simple_nested_form_for @product, html: { multipart: true }, :url => admin_brand_products_path(@brand) do |f| %>

  <%= render(:partial=>'form', :locals=>{:f=>f})%>
 
  
  <div class="form-group">
    <%= f.submit '新增', class: "btn btn-primary btn-lg" %>
    
  </div>

  <% end %>
</div>