config/routes.rb
Rails.application.routes.draw do

  
  root to: "pages#home"
  get '/about',to: 'pages#about'
  get '/contact', to: 'pages#contact'

  resources :brands, only: [:show, :index]
  resources :products, only: :show
  resources :subscribers, only: [:new, :create]

  
  namespace :admin do  
    get "/" => "administrators#new_session"
    post "/" => "administrators#create_session"
    delete "/" => "administrators#destroy_session"

    resources :brands do
      resources :products, shallow: true
    end
    resources :subscribers, only: [:index, :destroy]

    get 'pages/search'
    post 'products/search'
  end

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
    has_secure_password validations: false
    validates :account, presence: true, uniqueness: true
    validates :password, presence: true, on: :create, length:{minimum: 3}
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :imageable, polymorphic: true, touch: true
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  include Sluggable

  has_many :products, dependent: :destroy
  has_one :seo_info, as: :seoable

  has_many :banners, as: :imageable, dependent: :destroy
  has_one :display_photo, as: :imageable, dependent: :destroy

  validates :title, presence: true
  
  accepts_nested_attributes_for :banners, :reject_if => :all_blank, allow_destroy: true
  accepts_nested_attributes_for :display_photo, :reject_if => :all_blank, allow_destroy: true
  
  sluggable_column :title


end

app/models/concerns/sluggable.rb
# sluggable_ryan gem
module Sluggable
  extend ActiveSupport::Concern

  included do
    before_save :generate_slug!
    class_attribute :slug_column 
  end

  def to_param
    self.slug
  end

  def generate_slug!
    the_slug = to_slug( self.send(self.class.slug_column.to_sym) )
    obj = self.class.find_by slug: the_slug
    count = 2
    while obj && obj != self
      the_slug = append_suffix(the_slug, count)
      obj = self.class.find_by slug: the_slug
      count += 1
    end
    self.slug = the_slug
  end

  def append_suffix(str, count)
    if str.split('-').last.to_i != 0
      return str.split('-').slice(0...-1).join('-') + '-' + count.to_s
    else
      return str + '-' + count.to_s
    end
  end

  def to_slug(title)
    str = title.strip
    # \p{Han} will matcch all chinese characters
    str.gsub! /\s*[^A-Za-z0-9\p{Han}]\s*/, '-'
    str.gsub! /-+/, "-"
    str.downcase
  end

  module ClassMethods
    def sluggable_column(col_name)
      self.slug_column = col_name
    end
  end

end

app/models/display_photo.rb
class DisplayPhoto < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :imageable, polymorphic: true, touch: true
end

app/models/photo.rb
#TODO: deprecated. This class should be delete
class Photo < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :imageable, polymorphic: true, touch: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  include Sluggable

  belongs_to :brand
  has_one :seo_info, as: :seoable

  has_many :banners, as: :imageable, dependent: :destroy
  has_one :display_photo, as: :imageable, dependent: :destroy

  validates :title, presence: true

  accepts_nested_attributes_for :banners, :reject_if => :all_blank, allow_destroy: true
  accepts_nested_attributes_for :display_photo, :reject_if => :all_blank, allow_destroy: true

  sluggable_column :title



  # before_save :convert_youtube_url

  # def convert_youtube_url 
  #   if self.video_url?
  #     self.video_url = VideoInfo.new(self.video_url).embed_url
  #   end
  # end

  def youtube_embed_url
    VideoInfo.new(self.video_url).embed_url if self.video_url?
  end

end

app/models/seo_info.rb
class SeoInfo < ActiveRecord::Base

  belongs_to :seoable, polymorphic: true
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base

  after_save :subscribe

  validates :email, presence: true


  def subscribe
    @list_id = ENV['MAILCHIMP_LIST_ID']
    gb = Gibbon::API.new
    
    gb.lists.subscribe({
      :id => @list_id,
      :email => {:email => self.email}
    })
  end

  def created_today?
    self.created_at.to_date == Date.today
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  layout "admin"

  #before_action :authenticate_administrator!
  #before_action :admin_required, :except => [:new_session, :create_session]
  before_action :require_administrator, except: [:new_session, :create_session]

  

  helper_method :current_administrator, :logged_in?

  def require_administrator
    access_denied unless logged_in?
  end

  def access_denied
    flash[:error] = "Must be login to do that"
    redirect_to admin_path
  end

  def logged_in?
    !!current_administrator
  end

  def current_administrator
    @current_administrator ||= find_administrator
  end

  def find_administrator
    administrator = Administrator.find_by(id: session[:administrator_id])
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :find_brand, only: :show

  def index
    @brands = Brand.order(id: :asc)
  end

  def show
    @products = @brand.products.order(id: :desc).paginate(:page => params[:page], :per_page => 15)
  end


  private

  def find_brand
    @brand = Brand.includes(:products, :banners, :display_photo).find_by(slug: params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @products = Product.order(id: :desc).paginate(:page => params[:page], :per_page => 15) #.limit(6)
  end


  def about
  end

  def contact
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: :show

  def show
  end



  private

  def find_product
    @product = Product.includes(:brand, :banners, :display_photo).find_by(slug: params[:id])
  end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  
  def new
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      flash[:notice] = "您已成功註冊會員，請前往 Email 確認訂閱電子報，謝謝：）"
      redirect_to new_subscriber_path
    else
      flash.now[:error] = "註冊失敗，請確認欄位沒有空白"
      render :new
    end

  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:name, :line, :email, :phone_number)
  end


end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/pages/search.html.erb
<div class="pull-right">
<% @q = Product.ransack(params[:q])%>
<%= render :partial=>'shared/ransack_form', :locals=>{:q => @q}%>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>商品編號</th>
      <th>Product title</th>
      <th>Product Photo</th>
      <th>修改</th>
      <th>刪除</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'admin/products/product', collection: @products, as: :product %>
  </tbody>
</table>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watch</title>
  <%= stylesheet_link_tag 'bootstrap_and_customization.css' %>
  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>

</head>


<body>

  <div class="container">
    <%#= render "common/navbar" %>

    <%= render partial: 'layouts/messages' %>
    
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">

          <li> 
            <%= link_to("Admin Panel", admin_path) %> 
          </li>
          <hr>

          <li> 
            <%= link_to("收尋", admin_pages_search_path) %> 
          </li>
          <hr>

          <li> 
            <%= link_to("新增品牌", new_admin_brand_path) %> 
          </li>
          <hr>

          <li> 
            <%= link_to("品牌", "#") %> 
  
            <% Brand.all.each do |brand|%>

              <ol> <%= link_to(brand.title, admin_brand_path(brand)) %> </ol>
            <% end %>
          </li>
          <hr>

          <li> <%= link_to("訂閱者", admin_subscribers_path) %> 
          </li>
          <hr>

          <li class="li-sign_out">
            <%= link_to('登出', admin_path, method: :delete) if logged_in? %>
          </li>
        </ul>
      </div>
      <div class="col-md-offset-1 col-md-9 well">
        <%= yield %>
      </div>
      
    </div>
  </div>

  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watch180</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>


<%= render partial: 'shared/header' %>

<%= render partial: 'layouts/messages' %>
<%= yield %>
<%= render partial: 'shared/footer' %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
<%= yield :customize_js%>

</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.try(:errors).try(:any?) %>
  <div class="alert alert-danger">
    <ul>
      <% obj.errors.full_messages.each do |msg|%>
      <li> <%= msg %> </li>
      <%end%>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- 頁尾 -->
<div class="footer-bg hidden-xs">
    <div class="footer">
        <div class="container text-center footer-logo">
            <div class="text-center col-md-10 col-md-offset-1 col-xs-10 col-xs-offest-1">
                <%= image_tag('home06.png', class: "img-responsive col-md-4 col-md-offset-4") %>
                <!-- <img src="img/home06.png" class="img-responsive col-md-4 col-md-offset-4"> -->
            </div>
            <div class="text-center col-md-6 col-md-offset-3 hidden-xs footer_font ">
                </br>
                </br>
                <br>
                <h4>電話</h4>
                <h4>02-2558-8418 / 02-2556-1848</h4>
                <h4>信箱</h4>
                <h4>watch180tw@gmail.com</h4>
                <h4>營業時間</h4>
                <h4>營業時間 12:00PM ~ 20:30PM (週日休) </h4>
                <h4>地址</h4>
                <h4>台北市大同區民生西路180號</h4>
                <br>
                <p>站內所有資訊僅供參考，實際售價以店面交易價格為準</p>
            </div>
            <div class=" col-md-6 col-md-offset-3 visible-xs col-xs-12 ">
                </br>
                <div class="col-xs-12">
                    <br>
                </div>
                <div class="text-left col-xs-12">
                    <p>電話 02-2558-8418 / 02-2556-1848</p>
                    <p>信箱 watch180tw@gmail.com</p>
                    <p>營業時間 12:00PM ~ 20:30PM (週日休) </p>
                    <br>
                    <p>地址 台北市大同區民生西路180號</p>
                    <p>站內所有資訊僅供參考，實際售價以店面交易價格為準</p>
                </div>
            </div>
        </div>
    </div>
</div>
<nav class="navbar-f hidden-xs">
    <div class="container text-center">
        <div class="col-md-4 col-md-offset-4">
            <p class="rights"> 2015 Watch180 All rights reserved</p>
        </div>
        <div class="col-md-4 ">
            <a href="#header">
              <%= image_tag('top_c.png', class: "top-btn") %>
              <!-- <img src="img/top_c.png" class="top-btn"> -->
            </a>
        </div>
    </div>
</nav>

<!--手機版頁尾 -->
<div class="footer-bg visible-xs">
    <div class="footer-m">
        <div class="container text-center footer-logo">
            <div class="text-center col-md-10 col-md-offset-1 col-xs-10 col-xs-offest-1">
              <%= image_tag('home06.png', class: "img-responsive col-md-4 col-md-offset-4") %> 
              <!-- <img src="img/home06.png" class="img-responsive col-md-4 col-md-offset-4"> -->
            </div>
            <div class="text-center col-md-6 col-md-offset-3 hidden-xs ">
                </br>
                </br>
                <br>
                <h4>電話</h4>
                <h4>02-2558-8418 / 02-2556-1848</h4>
                <h4>信箱</h4>
                <h4>watch180tw@gmail.com</h4>
                <h4>營業時間</h4>
                <h4> 12:00PM ~ 20:30PM (週日休) </h4>
                <h4>地址</h4>
                <h4>台北市大同區民生西路180號</h4>
                <br>
                <p>站內所有資訊僅供參考，實際售價以店面交易價格為準</p>
            </div>
            <div class=" col-md-6 col-md-offset-3 visible-xs col-xs-12 ">
                </br>
                <div class="col-xs-12">
                    <br>
                </div>
                <div class="text-left col-xs-12">
                    <p>電話 02-2558-8418 / 02-2556-1848</p>
                    <p>信箱 watch180tw@gmail.com</p>
                    <p>營業時間 12:00PM ~ 20:30PM (週日休) </p>
                    <br>
                    <p>地址 台北市大同區民生西路180號</p>
                    <p>站內所有資訊僅供參考，實際售價以店面交易價格為準</p>
                </div>
            </div>
        </div>
    </div>
</div>

<nav class="navbar-f visible-xs">
    <div class="container text-center">
        <p class="rights"> 2015 Watch180 All rights reserved</p>
    </div>
</nav>

app/views/shared/_header.html.erb
<!-- header -->
<nav class="navbar navbar-inverse" id="header">
    <div class="container text-center">
        <!-- 導覽列標頭 -->
        <div class="navbar-header col-xs-12  col-md-2 col-md-offset-2">
            <%= link_to(root_path, class: "navbar-brand") do%>
              <%= image_tag("header.png") %>
            <%end %>
            <!-- <a class="navbar-brand" href="layout.html"> -->
                <!-- <img src="../watch180/img/header.png"> -->
            <!-- </a> -->
        </div>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <!-- 導覽列選項-->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav col-md-8 col-md-offset-2 col-xs-9">
                <li class="visible-xs">
                  <%= link_to(root_path) do%>
                    <p>新 進 商 品</p><b>New</b> <span class="sr-only">(current)</span>
                  <% end %>
                    <!-- <a href="layout.html">
                        <p>新 進 商 品</p><b>New</b> <span class="sr-only">(current)</span></a> -->
                </li>
                <li class="">
                  <%= link_to(about_path) do%>
                    <p>關 於 我 們</p><b>About</b> <span class="sr-only">(current)</span>
                  <% end %>
                   <!--  <a href="about.html">
                        <p>關 於 我 們</p><b>About</b> <span class="sr-only">(current)</span></a> -->
                </li>
                <li>
                  <%= link_to(brands_path) do%>
                    <p>品 牌 精 選</p><b>Brand</b>
                  <% end %>
                    <!-- <a href="brand.html">
                        <p>品 牌 精 選</p><b>Brand</b></a> -->
                </li>
                <li>
                  <%= link_to(contact_path) do%>
                    <p>聯 絡 我 們</p>
                    <b2>Contact Us</b2>
                  <% end %>
                    <!-- <a href="contact.html">
                        <p>聯 絡 我 們</p>
                        <b2>Contact Us</b2>
                    </a> -->
                </li>
                <li>
                  <%= link_to(new_subscriber_path) do%>
                    <p>加 入 會 員</p>
                    <b2>Join Member</b2>
                  <% end %>
                    <!-- <a href="join.html">
                        <p>加 入 會 員</p>
                        <b2>Join Member</b2>
                    </a> -->
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/shared/_ransack_form.html.erb
  <%= search_form_for q ,:url=> admin_products_search_path, method: :post, :class=>"navbar-form navbar-left", :role=>"search" do |f| %>
    <div class="form-group">
        <div class="input-group">
          <% value = params[:q][:number_or_title_or_description_cont] if params[:q]%>
          <%= f.search_field(:number_or_title_or_description_cont, value: value, :class=>"form-control input-nonhidden", :id=>"navbarInput-01", :type=>"search", :placeholder=>"Search") %>

          
          <span class="input-group-btn">

            <%= button_tag(:type => 'submit', :class => 'btn btn-search') do %>
                <span class="glyphicon glyphicon-search"></span>
            <% end %>

          </span>  
        </div>
    </div>
  <%end%>